// Code generated by MockGen. DO NOT EDIT.
// Source: ../domain/repositories.go
//
// Generated by this command:
//
//	mockgen -source=../domain/repositories.go -destination=repositories_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/solock/solock/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEntryRepository is a mock of EntryRepository interface.
type MockEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntryRepositoryMockRecorder
	isgomock struct{}
}

// MockEntryRepositoryMockRecorder is the mock recorder for MockEntryRepository.
type MockEntryRepositoryMockRecorder struct {
	mock *MockEntryRepository
}

// NewMockEntryRepository creates a new mock instance.
func NewMockEntryRepository(ctrl *gomock.Controller) *MockEntryRepository {
	mock := &MockEntryRepository{ctrl: ctrl}
	mock.recorder = &MockEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryRepository) EXPECT() *MockEntryRepositoryMockRecorder {
	return m.recorder
}

// ClearAll mocks base method.
func (m *MockEntryRepository) ClearAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearAll indicates an expected call of ClearAll.
func (mr *MockEntryRepositoryMockRecorder) ClearAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAll", reflect.TypeOf((*MockEntryRepository)(nil).ClearAll), ctx)
}

// Count mocks base method.
func (m *MockEntryRepository) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockEntryRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockEntryRepository)(nil).Count), ctx)
}

// Delete mocks base method.
func (m *MockEntryRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEntryRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEntryRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockEntryRepository) Get(ctx context.Context, id string) (*domain.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEntryRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEntryRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockEntryRepository) List(ctx context.Context) ([]*domain.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEntryRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEntryRepository)(nil).List), ctx)
}

// MarkSynced mocks base method.
func (m *MockEntryRepository) MarkSynced(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSynced", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSynced indicates an expected call of MarkSynced.
func (mr *MockEntryRepositoryMockRecorder) MarkSynced(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSynced", reflect.TypeOf((*MockEntryRepository)(nil).MarkSynced), ctx, id)
}

// Save mocks base method.
func (m *MockEntryRepository) Save(ctx context.Context, entry *domain.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockEntryRepositoryMockRecorder) Save(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEntryRepository)(nil).Save), ctx, entry)
}

// MockConfigRepository is a mock of ConfigRepository interface.
type MockConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockConfigRepositoryMockRecorder is the mock recorder for MockConfigRepository.
type MockConfigRepositoryMockRecorder struct {
	mock *MockConfigRepository
}

// NewMockConfigRepository creates a new mock instance.
func NewMockConfigRepository(ctrl *gomock.Controller) *MockConfigRepository {
	mock := &MockConfigRepository{ctrl: ctrl}
	mock.recorder = &MockConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigRepository) EXPECT() *MockConfigRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConfigRepository) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfigRepositoryMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigRepository)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockConfigRepository) Set(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockConfigRepositoryMockRecorder) Set(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockConfigRepository)(nil).Set), ctx, key, value)
}

// MockSyncStateRepository is a mock of SyncStateRepository interface.
type MockSyncStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSyncStateRepositoryMockRecorder
	isgomock struct{}
}

// MockSyncStateRepositoryMockRecorder is the mock recorder for MockSyncStateRepository.
type MockSyncStateRepositoryMockRecorder struct {
	mock *MockSyncStateRepository
}

// NewMockSyncStateRepository creates a new mock instance.
func NewMockSyncStateRepository(ctrl *gomock.Controller) *MockSyncStateRepository {
	mock := &MockSyncStateRepository{ctrl: ctrl}
	mock.recorder = &MockSyncStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncStateRepository) EXPECT() *MockSyncStateRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSyncStateRepository) Get(ctx context.Context) (*domain.SyncState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*domain.SyncState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSyncStateRepositoryMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSyncStateRepository)(nil).Get), ctx)
}

// Set mocks base method.
func (m *MockSyncStateRepository) Set(ctx context.Context, state *domain.SyncState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSyncStateRepositoryMockRecorder) Set(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSyncStateRepository)(nil).Set), ctx, state)
}

// MockVaultRepository is a mock of VaultRepository interface.
type MockVaultRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVaultRepositoryMockRecorder
	isgomock struct{}
}

// MockVaultRepositoryMockRecorder is the mock recorder for MockVaultRepository.
type MockVaultRepositoryMockRecorder struct {
	mock *MockVaultRepository
}

// NewMockVaultRepository creates a new mock instance.
func NewMockVaultRepository(ctrl *gomock.Controller) *MockVaultRepository {
	mock := &MockVaultRepository{ctrl: ctrl}
	mock.recorder = &MockVaultRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultRepository) EXPECT() *MockVaultRepositoryMockRecorder {
	return m.recorder
}

// AddEntry mocks base method.
func (m *MockVaultRepository) AddEntry(ctx context.Context, index uint32, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEntry", ctx, index, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEntry indicates an expected call of AddEntry.
func (mr *MockVaultRepositoryMockRecorder) AddEntry(ctx, index, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEntry", reflect.TypeOf((*MockVaultRepository)(nil).AddEntry), ctx, index, data)
}

// DeleteEntry mocks base method.
func (m *MockVaultRepository) DeleteEntry(ctx context.Context, index uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEntry", ctx, index)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry.
func (mr *MockVaultRepositoryMockRecorder) DeleteEntry(ctx, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockVaultRepository)(nil).DeleteEntry), ctx, index)
}

// DeployProgram mocks base method.
func (m *MockVaultRepository) DeployProgram(ctx context.Context, programBinary []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeployProgram", ctx, programBinary)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeployProgram indicates an expected call of DeployProgram.
func (mr *MockVaultRepositoryMockRecorder) DeployProgram(ctx, programBinary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployProgram", reflect.TypeOf((*MockVaultRepository)(nil).DeployProgram), ctx, programBinary)
}

// Exists mocks base method.
func (m *MockVaultRepository) Exists(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockVaultRepositoryMockRecorder) Exists(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockVaultRepository)(nil).Exists), ctx)
}

// GetBalance mocks base method.
func (m *MockVaultRepository) GetBalance(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockVaultRepositoryMockRecorder) GetBalance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockVaultRepository)(nil).GetBalance), ctx)
}

// GetEntriesBatch mocks base method.
func (m *MockVaultRepository) GetEntriesBatch(ctx context.Context, indices []uint32) (map[uint32]*domain.EntryAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntriesBatch", ctx, indices)
	ret0, _ := ret[0].(map[uint32]*domain.EntryAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntriesBatch indicates an expected call of GetEntriesBatch.
func (mr *MockVaultRepositoryMockRecorder) GetEntriesBatch(ctx, indices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntriesBatch", reflect.TypeOf((*MockVaultRepository)(nil).GetEntriesBatch), ctx, indices)
}

// GetEntry mocks base method.
func (m *MockVaultRepository) GetEntry(ctx context.Context, index uint32) (*domain.EntryAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry", ctx, index)
	ret0, _ := ret[0].(*domain.EntryAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockVaultRepositoryMockRecorder) GetEntry(ctx, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntry", reflect.TypeOf((*MockVaultRepository)(nil).GetEntry), ctx, index)
}

// GetMeta mocks base method.
func (m *MockVaultRepository) GetMeta(ctx context.Context) (*domain.VaultMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeta", ctx)
	ret0, _ := ret[0].(*domain.VaultMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeta indicates an expected call of GetMeta.
func (mr *MockVaultRepositoryMockRecorder) GetMeta(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeta", reflect.TypeOf((*MockVaultRepository)(nil).GetMeta), ctx)
}

// Initialize mocks base method.
func (m *MockVaultRepository) Initialize(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockVaultRepositoryMockRecorder) Initialize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockVaultRepository)(nil).Initialize), ctx)
}

// IsProgramDeployed mocks base method.
func (m *MockVaultRepository) IsProgramDeployed(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProgramDeployed", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProgramDeployed indicates an expected call of IsProgramDeployed.
func (mr *MockVaultRepositoryMockRecorder) IsProgramDeployed(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProgramDeployed", reflect.TypeOf((*MockVaultRepository)(nil).IsProgramDeployed), ctx)
}

// Reset mocks base method.
func (m *MockVaultRepository) Reset(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockVaultRepositoryMockRecorder) Reset(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockVaultRepository)(nil).Reset), ctx)
}

// UpdateEntry mocks base method.
func (m *MockVaultRepository) UpdateEntry(ctx context.Context, index uint32, data []byte, expectedUpdatedAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEntry", ctx, index, data, expectedUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEntry indicates an expected call of UpdateEntry.
func (mr *MockVaultRepositoryMockRecorder) UpdateEntry(ctx, index, data, expectedUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntry", reflect.TypeOf((*MockVaultRepository)(nil).UpdateEntry), ctx, index, data, expectedUpdatedAt)
}
