// Code generated by MockGen. DO NOT EDIT.
// Source: ../domain/services.go
//
// Generated by this command:
//
//	mockgen -source=../domain/services.go -destination=services_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/solock/solock/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyDeriver is a mock of KeyDeriver interface.
type MockKeyDeriver struct {
	ctrl     *gomock.Controller
	recorder *MockKeyDeriverMockRecorder
	isgomock struct{}
}

// MockKeyDeriverMockRecorder is the mock recorder for MockKeyDeriver.
type MockKeyDeriverMockRecorder struct {
	mock *MockKeyDeriver
}

// NewMockKeyDeriver creates a new mock instance.
func NewMockKeyDeriver(ctrl *gomock.Controller) *MockKeyDeriver {
	mock := &MockKeyDeriver{ctrl: ctrl}
	mock.recorder = &MockKeyDeriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyDeriver) EXPECT() *MockKeyDeriverMockRecorder {
	return m.recorder
}

// Derive mocks base method.
func (m *MockKeyDeriver) Derive(password string) (*domain.DerivedKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Derive", password)
	ret0, _ := ret[0].(*domain.DerivedKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Derive indicates an expected call of Derive.
func (mr *MockKeyDeriverMockRecorder) Derive(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Derive", reflect.TypeOf((*MockKeyDeriver)(nil).Derive), password)
}

// MockCryptoService is a mock of CryptoService interface.
type MockCryptoService struct {
	ctrl     *gomock.Controller
	recorder *MockCryptoServiceMockRecorder
	isgomock struct{}
}

// MockCryptoServiceMockRecorder is the mock recorder for MockCryptoService.
type MockCryptoServiceMockRecorder struct {
	mock *MockCryptoService
}

// NewMockCryptoService creates a new mock instance.
func NewMockCryptoService(ctrl *gomock.Controller) *MockCryptoService {
	mock := &MockCryptoService{ctrl: ctrl}
	mock.recorder = &MockCryptoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryptoService) EXPECT() *MockCryptoServiceMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockCryptoService) Decrypt(data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockCryptoServiceMockRecorder) Decrypt(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockCryptoService)(nil).Decrypt), data)
}

// Encrypt mocks base method.
func (m *MockCryptoService) Encrypt(data []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockCryptoServiceMockRecorder) Encrypt(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockCryptoService)(nil).Encrypt), data)
}
